create table if not exists public.universities (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  is_active boolean not null default true,
  is_suggested boolean not null default false,
  suggested_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- RLS
alter table public.universities enable row level security;

-- Anyone authenticated can read active universities
create policy "Public read universities"
  on public.universities for select
  using (true);

-- Only service role can insert/update/delete (admin actions use service role client)
create policy "Service role manages universities"
  on public.universities for all
  using (auth.role() = 'service_role');

-- Seed from PH_UNIVERSITIES (src/components/university-select.tsx)
insert into public.universities (name, is_active, is_suggested)
values
  ('University of the Philippines Diliman', true, false),
  ('University of the Philippines Manila', true, false),
  ('University of the Philippines Los Baños', true, false),
  ('University of the Philippines Visayas', true, false),
  ('University of the Philippines Mindanao', true, false),
  ('De La Salle University', true, false),
  ('Ateneo de Manila University', true, false),
  ('University of Santo Tomas', true, false),
  ('Far Eastern University', true, false),
  ('Mapúa University', true, false),
  ('Polytechnic University of the Philippines', true, false),
  ('University of the East', true, false),
  ('Adamson University', true, false),
  ('San Beda University', true, false),
  ('Letran College', true, false),
  ('Pamantasan ng Lungsod ng Maynila', true, false),
  ('National University Philippines', true, false),
  ('Philippine Normal University', true, false),
  ('Philippine Women''s University', true, false),
  ('Saint Louis University', true, false),
  ('University of Asia and the Pacific', true, false),
  ('Miriam College', true, false),
  ('Assumption College', true, false),
  ('College of Saint Benilde', true, false),
  ('Benilde', true, false),
  ('University of Northern Philippines', true, false),
  ('Mariano Marcos State University', true, false),
  ('Don Mariano Marcos Memorial State University', true, false),
  ('University of the Cordilleras', true, false),
  ('Baguio Central University', true, false),
  ('Saint Louis University Baguio', true, false),
  ('Benguet State University', true, false),
  ('Nueva Ecija University of Science and Technology', true, false),
  ('Central Luzon State University', true, false),
  ('Holy Angel University', true, false),
  ('Angeles University Foundation', true, false),
  ('Pampanga State Agricultural University', true, false),
  ('Tarlac State University', true, false),
  ('Bataan Peninsula State University', true, false),
  ('Cavite State University', true, false),
  ('Laguna State Polytechnic University', true, false),
  ('Batangas State University', true, false),
  ('Lyceum of the Philippines University', true, false),
  ('De La Salle University Dasmariñas', true, false),
  ('University of Batangas', true, false),
  ('Palawan State University', true, false),
  ('Western Philippines University', true, false),
  ('Bicol University', true, false),
  ('Ateneo de Naga University', true, false),
  ('University of Nueva Caceres', true, false),
  ('Camarines Sur Polytechnic Colleges', true, false),
  ('West Visayas State University', true, false),
  ('Iloilo Science and Technology University', true, false),
  ('Central Philippine University', true, false),
  ('University of San Agustin', true, false),
  ('John B. Lacson Foundation Maritime University', true, false),
  ('Capiz State University', true, false),
  ('Aklan State University', true, false),
  ('University of the Philippines Cebu', true, false),
  ('University of Cebu', true, false),
  ('University of San Carlos', true, false),
  ('Cebu Institute of Technology University', true, false),
  ('Cebu Technological University', true, false),
  ('University of San Jose-Recoletos', true, false),
  ('Southwestern University PHINMA', true, false),
  ('Silliman University', true, false),
  ('Saint Paul University Dumaguete', true, false),
  ('Negros Oriental State University', true, false),
  ('Bohol Island State University', true, false),
  ('Eastern Visayas State University', true, false),
  ('Leyte Normal University', true, false),
  ('Naval State University', true, false),
  ('University of Eastern Philippines', true, false),
  ('Zamboanga State College of Marine Sciences and Technology', true, false),
  ('Western Mindanao State University', true, false),
  ('Ateneo de Zamboanga University', true, false),
  ('Mindanao State University Iligan', true, false),
  ('Central Mindanao University', true, false),
  ('Xavier University Ateneo de Cagayan', true, false),
  ('Capitol University', true, false),
  ('Liceo de Cagayan University', true, false),
  ('Davao del Norte State College', true, false),
  ('Holy Cross of Davao College', true, false),
  ('Ateneo de Davao University', true, false),
  ('University of Southeastern Philippines', true, false),
  ('University of Mindanao', true, false),
  ('Southern Philippines Medical Center College of Medicine', true, false),
  ('Notre Dame of Marbel University', true, false),
  ('Notre Dame University Cotabato', true, false),
  ('Mindanao State University General Santos', true, false),
  ('Sultan Kudarat State University', true, false),
  ('Caraga State University', true, false),
  ('Agusan del Sur State College of Agriculture and Technology', true, false),
  ('Mindanao State University Marawi', true, false),
  ('Lanao del Norte Agricultural College', true, false),
  ('Mapúa Malayan Colleges Mindanao', true, false),
  ('AMACC', true, false),
  ('AMA Computer University', true, false),
  ('STI College', true, false),
  ('Systems Technology Institute', true, false),
  ('Informatics College', true, false),
  ('Philippine Science High School', true, false),
  ('Other', true, false)
on conflict (name) do nothing;
